const IM_KEY='investmaster-v2';
const imState=JSON.parse(localStorage.getItem(IM_KEY)||'{"completed":[],"notes":{},"rules":{}}');
const saveState=()=>{localStorage.setItem(IM_KEY,JSON.stringify(imState));updateGlobalProgress()};
const updateGlobalProgress=()=>document.querySelectorAll('[data-global-progress]').forEach(el=>el.textContent=Math.min(100,Math.round((imState.completed.length/80)*100))+'%');
const exampleBlock=(id,text)=>text?`<div class="example-wrap"><button type="button" class="example-toggle" data-example-toggle="${id}">예시 답안 보기</button><div class="example-box" data-example-box="${id}" hidden><b>예시 답안</b><p>${text}</p></div></div>`:'';
const wireExamples=()=>document.querySelectorAll('[data-example-toggle]').forEach(b=>b.onclick=()=>{const box=document.querySelector(`[data-example-box="${CSS.escape(b.dataset.exampleToggle)}"]`);if(!box)return;const wasHidden=box.hasAttribute('hidden');box.toggleAttribute('hidden');b.textContent=wasHidden?'예시 답안 닫기':'예시 답안 보기'});
function renderJourney(){const host=document.querySelector('#journeyList');if(!host||!window.PARTS)return;host.innerHTML=PARTS.map(p=>`<a class="journey-row" href="curriculum.html?part=${p.id}"><span>${String(p.id).padStart(2,'0')}</span><div><small>${p.kicker}</small><h3>${p.title}</h3><p>${p.summary}</p></div><b>${p.range}</b><i>↗</i></a>`).join('')}
document.querySelectorAll('[data-decision]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-decision]').forEach(x=>x.classList.toggle('selected',x===btn));const m={buy:'좋은 기업과 좋은 투자는 다릅니다. 지불한 가격이 미래 수익률을 결정합니다.',avoid:'비싸다는 인상만으로는 부족합니다. 현재 가격이 요구하는 성장률을 계산해야 합니다.',wait:'좋습니다. Reverse DCF로 가격에 담긴 기대를 먼저 확인한 뒤 현실성과 비교하세요.'};document.querySelector('#decisionFeedback').textContent=m[btn.dataset.decision]});
renderJourney();updateGlobalProgress();
