const partId=Math.min(12,Math.max(1,+(new URLSearchParams(location.search).get('part')||1)));
const part=PARTS.find(p=>p.id===partId);
const concepts={1:['가격은 오늘 지불하는 숫자이고, 가치는 미래에 받을 현금의 현재값입니다.','위험은 흔들림만이 아니라 영구적으로 자본을 잃을 가능성입니다.','확률 × 손익비 × 베팅 크기를 함께 봐야 오래 살아남습니다.'],2:['편향은 제거 대상이 아니라 발견하고 통제할 대상입니다.','결정의 질과 결과의 질을 분리해야 운을 실력으로 착각하지 않습니다.'],3:['매출은 가격 × 수량처럼 관찰 가능한 동인으로 분해합니다.','경쟁우위는 높은 이익률보다 그 이익률을 지키는 구조입니다.'],4:['세 재무제표는 서로 연결된 한 편의 이야기입니다.','EPS 증가가 현금 창출과 주당 가치 증가를 뜻하는지 확인합니다.'],5:['이익이 현금이 되는 비율과 재투자한 자본의 수익률을 함께 봅니다.','ROIC가 높아도 재투자 공간이 없다면 복리 속도는 제한됩니다.'],6:['좋은 기업은 높은 ROIC를 긴 시간 유지하며 현금을 다시 높은 수익률로 투자합니다.'],7:['멀티플은 성장, 자본수익률, 위험, 지속기간을 압축한 가격표입니다.'],8:['DCF는 정답 기계가 아니라 가정을 투명하게 만드는 사고 도구입니다.','Reverse DCF는 현재 가격이 요구하는 미래를 역산합니다.'],9:['거장의 결론보다 Universe·Edge·Signal·Sizing·Exit의 구조를 복제합니다.'],10:['매크로 숫자보다 예상과의 차이, 정책 반응, 자산 가격 전달 경로를 봅니다.'],11:['종목 수가 아니라 위험요인의 수가 진짜 분산을 결정합니다.','포지션 크기는 확신이 아니라 틀렸을 때의 손실에서 출발합니다.'],12:['좋은 시스템은 무엇을 할지뿐 아니라 무엇을 하지 않을지를 명확히 합니다.']};
function nav(){document.querySelector('#partNav').innerHTML=PARTS.map(p=>`<a class="${p.id===partId?'active':''}" href="?part=${p.id}"><i style="background:${p.color}"></i><span>PART ${String(p.id).padStart(2,'0')}</span><b>${p.title}</b><small>${p.range}</small></a>`).join('')}
function hero(){document.querySelector('#courseHero').style.setProperty('--part-color',part.color);document.querySelector('#courseHero').innerHTML=`<p class="eyebrow">PART ${String(part.id).padStart(2,'0')} · ${part.kicker}</p><h1>${part.title}</h1><p>${part.summary}</p><div class="lesson-chips">${part.lessons.map((l,i)=>`<label><input type="checkbox" data-complete="${part.id}-${i}"><span>${l}</span></label>`).join('')}</div>`}
const n=v=>new Intl.NumberFormat('ko-KR',{maximumFractionDigits:1}).format(v);
function activity(){
 if(part.activity==='compound')return `<div class="calculator"><label>시작금액 <input id="principal" type="range" min="100" max="10000" value="1000"><b id="principalOut"></b></label><label>연 수익률 <input id="rate" type="range" min="1" max="30" value="10"><b id="rateOut"></b></label><label>투자기간 <input id="years" type="range" min="1" max="40" value="20"><b id="yearsOut"></b></label><div class="calc-result"><small>복리 후 자산</small><strong id="compoundOut"></strong><span id="compoundNote"></span></div></div>`;
 if(part.activity==='dcf'||part.activity==='multiple')return `<div class="calculator"><label>현재 FCF <input id="fcf" type="range" min="10" max="500" value="100"><b id="fcfOut"></b></label><label>5년 성장률 <input id="growth" type="range" min="0" max="40" value="15"><b id="growthOut"></b></label><label>할인율 <input id="discount" type="range" min="5" max="20" value="10"><b id="discountOut"></b></label><div class="calc-result"><small>5년 뒤 FCF의 현재가치</small><strong id="dcfOut"></strong><span>가정 하나가 가치평가를 얼마나 바꾸는지 움직여 보세요.</span></div></div>`;
 if(part.activity==='roic'||part.activity==='quality')return `<div class="formula-lab"><div><span>NOPAT</span><input id="nopat" type="number" value="180"></div><b>÷</b><div><span>투하자본</span><input id="capital" type="number" value="1000"></div><b>=</b><strong id="roicOut">18%</strong></div><p class="hint">높은 ROIC가 경쟁우위 때문인지, 일시적 호황이나 낮은 분모 때문인지 한 번 더 묻습니다.</p>`;
 if(part.activity==='revenue'||part.activity==='margin')return `<div class="driver-grid"><button data-driver="price"><b>가격 +10%</b><span>가격결정력은 있지만 수요가 줄 수 있습니다.</span></button><button data-driver="volume"><b>판매량 +10%</b><span>규모는 커지지만 변동비와 CapEx를 확인합니다.</span></button><button data-driver="mix"><b>고마진 Mix +10%</b><span>매출보다 이익이 빠르게 성장할 수 있습니다.</span></button></div><p id="driverResult" class="hint">성장 동인을 선택해 경제성의 차이를 확인하세요.</p>`;
 return `<div class="scenario"><div class="scenario-chain"><span>새 정보</span><i>→</i><span>시장 기대</span><i>→</i><span>가격 반응</span><i>→</i><span>내 행동</span></div><textarea data-note="chain-${part.id}" placeholder="각 화살표 사이의 인과관계를 내 말로 적어보세요."></textarea></div>`;
}
function panel(tab='concept'){
 const host=document.querySelector('#lessonPanel');
 if(tab==='concept')host.innerHTML=`<article class="lesson-panel"><div class="panel-label">핵심 개념</div><h2>먼저, 이 문장들을<br>설명할 수 있어야 합니다.</h2><ol class="concept-list">${(concepts[part.id]||[]).map((x,i)=>`<li><b>0${i+1}</b><p>${x}</p></li>`).join('')}</ol><div class="lesson-map"><span>사실</span><i>→</i><span>해석</span><i>→</i><span>기대</span><i>→</i><span>가격</span><i>→</i><span>행동</span></div></article>`;
 if(tab==='case')host.innerHTML=`<article class="lesson-panel case-panel"><div class="panel-label">CASE STUDY</div><h2>${part.caseTitle}</h2><p class="case-lead">${part.caseText}</p><div class="case-split"><div><small>먼저 관찰</small><h3>무엇이 사실인가?</h3><textarea data-note="fact-${part.id}" placeholder="숫자와 확인 가능한 사실만 적어보세요."></textarea></div><div><small>그 다음 판단</small><h3>가격에 무엇이 반영됐나?</h3><textarea data-note="expectation-${part.id}" placeholder="시장의 기대와 내 해석을 구분해 적어보세요."></textarea></div></div></article>`;
 if(tab==='practice')host.innerHTML=`<article class="lesson-panel"><div class="panel-label">INTERACTIVE PRACTICE</div><h2>숫자를 움직이면<br>판단이 어떻게 달라질까요?</h2>${activity()}</article>`;
 if(tab==='rule')host.innerHTML=`<article class="lesson-panel rule-panel"><div class="panel-label">MY RULE</div><h2>배운 것을 내 언어로<br>한 줄 규칙으로 남기세요.</h2><textarea data-rule="${part.id}" placeholder="예: 좋은 기업이라는 이유만으로 사지 않는다. 가격이 요구하는 성장률을 먼저 역산한다."></textarea><div class="pass-card"><div><small>PASS CRITERIA</small><b>이 Part를 통과하려면</b><p>핵심 개념을 사례에 적용하고, 반대 논리와 무효화 조건까지 내 말로 설명할 수 있어야 합니다.</p></div><button id="completePart">PART ${String(part.id).padStart(2,'0')} 완료하기</button></div></article>`;
 wire(tab)
}
function wire(tab){
 document.querySelectorAll('[data-note]').forEach(x=>{x.value=imState.notes[x.dataset.note]||'';x.oninput=()=>{imState.notes[x.dataset.note]=x.value;saveState()}});
 document.querySelectorAll('[data-rule]').forEach(x=>{x.value=imState.rules[x.dataset.rule]||'';x.oninput=()=>{imState.rules[x.dataset.rule]=x.value;saveState()}});
 if(tab==='practice'&&document.querySelector('#principal')){const pEl=document.querySelector('#principal'),rEl=document.querySelector('#rate'),yEl=document.querySelector('#years');const calc=()=>{let p=+pEl.value,r=+rEl.value,y=+yEl.value;document.querySelector('#principalOut').textContent=n(p)+'만원';document.querySelector('#rateOut').textContent=r+'%';document.querySelector('#yearsOut').textContent=y+'년';document.querySelector('#compoundOut').textContent=n(p*(1+r/100)**y)+'만원';document.querySelector('#compoundNote').textContent=`원금의 ${n((1+r/100)**y)}배`};document.querySelectorAll('.calculator input').forEach(x=>x.oninput=calc);calc()}
 if(tab==='practice'&&document.querySelector('#fcf')){const f=document.querySelector('#fcf'),g=document.querySelector('#growth'),d=document.querySelector('#discount');const calc=()=>{document.querySelector('#fcfOut').textContent=f.value+'억';document.querySelector('#growthOut').textContent=g.value+'%';document.querySelector('#discountOut').textContent=d.value+'%';document.querySelector('#dcfOut').textContent=n(+f.value*(1+g.value/100)**5/(1+d.value/100)**5)+'억원'};document.querySelectorAll('.calculator input').forEach(x=>x.oninput=calc);calc()}
 if(tab==='practice'&&document.querySelector('#nopat')){const np=document.querySelector('#nopat'),cap=document.querySelector('#capital');const calc=()=>document.querySelector('#roicOut').textContent=n(np.value/cap.value*100)+'%';np.oninput=cap.oninput=calc}
 document.querySelectorAll('[data-driver]').forEach(x=>x.onclick=()=>{document.querySelectorAll('[data-driver]').forEach(y=>y.classList.toggle('selected',x===y));document.querySelector('#driverResult').textContent=x.querySelector('span').textContent});
 const complete=document.querySelector('#completePart');if(complete){complete.classList.toggle('done',imState.completed.includes('part-'+part.id));complete.textContent=imState.completed.includes('part-'+part.id)?'✓ 완료했습니다':`PART ${String(part.id).padStart(2,'0')} 완료하기`;complete.onclick=()=>{const k='part-'+part.id;if(!imState.completed.includes(k))imState.completed.push(k);saveState();panel('rule')}}
}
function checks(){document.querySelectorAll('[data-complete]').forEach(x=>{x.checked=imState.completed.includes(x.dataset.complete);x.onchange=()=>{imState.completed=imState.completed.filter(k=>k!==x.dataset.complete);if(x.checked)imState.completed.push(x.dataset.complete);saveState()}})}
function pager(){document.querySelector('#coursePager').innerHTML=`${partId>1?`<a href="?part=${partId-1}">← PART ${String(partId-1).padStart(2,'0')}</a>`:'<span></span>'}${partId<12?`<a href="?part=${partId+1}">PART ${String(partId+1).padStart(2,'0')} →</a>`:'<a href="system.html">시스템 만들기 →</a>'}`}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));panel(b.dataset.tab)});nav();hero();checks();panel();pager();updateGlobalProgress();
