const PARTS=[
 {id:1,kicker:'FOUNDATION',title:'투자라는 게임',range:'01—06',summary:'가격·가치·복리·위험·확률을 통해 투자자의 기본 언어를 만듭니다.',color:'#db6b45',lessons:['저축·투자·투기의 차이','주식을 산다는 것의 의미','가격과 가치','복리','수익과 위험','확률적 사고'],caseTitle:'10년 복리의 착시',caseText:'연 15% 수익 뒤 -50% 손실을 입으면 단순 평균과 실제 자산은 얼마나 다를까요?',activity:'compound'},
 {id:2,kicker:'BEHAVIOR',title:'투자자의 가장 큰 적',range:'07—11',summary:'편향을 알아차리고 결정과 결과를 분리하는 투자 일지를 만듭니다.',color:'#b65d70',lessons:['반복되는 투자 실패','FOMO','공포','확증편향','결과편향과 투자 일지'],caseTitle:'수익 난 잘못된 투자',caseText:'근거 없이 산 종목이 40% 올랐습니다. 좋은 결정이었을까요?',activity:'bias'},
 {id:3,kicker:'BUSINESS',title:'기업이라는 생명체',range:'12—17',summary:'매출 공식, 비용 구조, 산업과 경쟁우위를 하나의 사업 모델로 연결합니다.',color:'#2d6b58',lessons:['기업은 어떻게 돈을 버는가','매출의 구조','비용 구조','산업 크기','경쟁 구조','경쟁우위'],caseTitle:'두 카페의 다른 성장',caseText:'같은 매출 성장도 가격 인상과 신규 점포 증가는 전혀 다른 경제성을 만듭니다.',activity:'revenue'},
 {id:4,kicker:'STATEMENTS',title:'재무제표라는 언어',range:'18—24',summary:'손익계산서와 재무상태표를 암기가 아닌 기업의 이야기로 읽습니다.',color:'#4f6994',lessons:['매출','Gross Margin','Operating Margin','EPS','자산','부채','자본'],caseTitle:'EPS가 늘었는데도',caseText:'자사주 매입으로 EPS는 늘었지만 영업이익은 그대로라면 기업은 성장한 걸까요?',activity:'margin'},
 {id:5,kicker:'CASH & QUALITY',title:'현금흐름과 기업의 질',range:'25—32',summary:'FCF·운전자본·ROIC를 통해 회계이익 뒤의 진짜 경제성을 찾습니다.',color:'#82643d',lessons:['현금흐름표','EBITDA의 함정','CapEx','Free Cash Flow','Working Capital','ROE','ROIC','Incremental ROIC'],caseTitle:'성장할수록 현금이 부족하다',caseText:'매출은 늘지만 재고와 매출채권이 더 빠르게 늘어나는 기업을 해부합니다.',activity:'roic'},
 {id:6,kicker:'QUALITY',title:'좋은 기업을 찾는 법',range:'33',summary:'높은 재투자수익률과 긴 성장 활주로가 복리 기업을 만드는 과정을 봅니다.',color:'#397665',lessons:['좋은 기업의 조건과 Terry Smith'],caseTitle:'높은 ROIC의 지속 가능성',caseText:'높은 수익률보다 그것을 오래 유지하고 재투자할 공간이 있는지가 중요합니다.',activity:'quality'},
 {id:7,kicker:'VALUATION',title:'기업의 가격표',range:'34—38',summary:'PER부터 PEG까지, 모든 배수 뒤에 있는 성장·수익·위험을 읽습니다.',color:'#9d5b39',lessons:['PER','PBR','EV/EBITDA','EV/Sales','PEG와 Multiples의 본질'],caseTitle:'PER 40배가 10배보다 싼 경우',caseText:'성장률, 자본수익률, 지속기간을 함께 놓고 두 기업을 비교합니다.',activity:'multiple'},
 {id:8,kicker:'INTRINSIC VALUE',title:'기업가치를 직접 계산한다',range:'39—47',summary:'현금흐름 예측부터 Reverse DCF까지 가격에 담긴 기대를 숫자로 바꿉니다.',color:'#243f66',lessons:['화폐의 시간가치','현금흐름 Forecast','할인율','WACC','Terminal Value','EV에서 Equity Value로','DDM','Residual Income','Reverse DCF'],caseTitle:'가격이 요구하는 성장률',caseText:'목표가격을 맞히는 대신 현재 가격을 정당화하는 성장률을 역산합니다.',activity:'dcf'},
 {id:9,kicker:'MASTERS LAB',title:'투자 거장 연구실',range:'PLAYBOOK',summary:'서로 모순되는 18명의 철학을 같은 질문으로 비교해 내 규칙만 남깁니다.',color:'#704b72',lessons:['가치의 원형','위대한 기업','성장주','역발상과 사이클','집중투자와 숏','추세추종','확률과 위험','글로벌 매크로','자산배분'],caseTitle:'Buffett과 Minervini가 충돌할 때',caseText:'기업가치와 가격 추세가 반대 방향이라면 누구의 도구를 언제 쓸까요?',activity:'masters'},
 {id:10,kicker:'MACRO',title:'Macro로 세계를 확장한다',range:'48—57',summary:'성장·물가·신용·금리를 기업 이익과 자산 가격으로 연결합니다.',color:'#3b6e80',lessons:['GDP','Growth','Inflation','Employment','Productivity','Money','Credit','Banking','Central Bank','Monetary Policy와 금리·사이클'],caseTitle:'좋은 고용이 나쁜 뉴스가 되는 날',caseText:'숫자 → 예상 차이 → 금리 → 할인율 → 주가의 연결 고리를 추적합니다.',activity:'macro'},
 {id:11,kicker:'PORTFOLIO',title:'포트폴리오의 최종 단계',range:'58—78',summary:'개별 아이디어를 상관관계·포지션 크기·리밸런싱 규칙으로 묶습니다.',color:'#53624c',lessons:['기대수익과 분산','공분산과 상관관계','분산투자와 효율적 경계','CAPM·Alpha·Beta','Factor Investing','Position Sizing','집중과 분산','최적화와 Black-Litterman','리밸런싱·위험예산·성과분해'],caseTitle:'좋은 종목 10개면 분산일까',caseText:'모두 같은 위험요인에 노출됐다면 종목 수가 늘어도 포트폴리오는 하나입니다.',activity:'portfolio'},
 {id:12,kicker:'YOUR SYSTEM',title:'나만의 투자 시스템',range:'79—80',summary:'나의 Edge와 철학을 정의하고 분석·매수·매도 규칙을 문서화합니다.',color:'#15231d',lessons:['나는 어떤 투자자인가','Investment Philosophy 작성'],caseTitle:'무엇을 쓰고 무엇을 버릴 것인가',caseText:'모든 전략을 섞지 않고 나의 시간·성향·능력에 맞는 일관된 시스템을 고릅니다.',activity:'system'}
];
const MASTERS=[['Graham','Valuation','안전마진','가격이 가치보다 충분히 낮은가?'],['Buffett','Business','좋은 기업과 복리','10년 보유해도 좋은 사업인가?'],['Munger','Mental Models','다학제 사고','내가 놓친 인센티브는 무엇인가?'],['Lynch','Observation','성장과 가격','이 기업은 어떤 유형인가?'],['Terry Smith','Quality','ROIC와 장기보유','재투자할수록 강해지는가?'],['Klarman','Downside','원금 보전','틀렸을 때 얼마나 잃는가?'],['Howard Marks','Cycle','2차적 사고','합의와 다른 내 생각은 무엇인가?'],['Einhorn','Variant View','시장의 오류','숫자에서 틀린 이야기가 보이는가?'],['Minervini','Momentum','가격도 정보','추세가 내 논리를 확인하는가?'],['Livermore','Trend','시장과 싸우지 않기','손실을 빠르게 인정할 수 있는가?'],['Seykota','System','손실 제한','규칙을 예외 없이 실행하는가?'],['Larry Hite','Probability','생존','한 번 틀려도 살아남는가?'],['Niederhoffer','Statistics','Tail Risk','과거 패턴이 깨질 때 무엇이 남나?'],['Tudor Jones','Macro / Trend','비대칭 베팅','상방 대비 하방이 제한됐는가?'],['Druckenmiller','Macro','확신과 집중','Fat pitch인가 평범한 기회인가?'],['Soros','Reflexivity','피드백 루프','가격이 현실을 바꾸고 있는가?'],['Bogle','Cost','시장을 소유하기','비용 뒤에 남는 수익은 얼마인가?'],['Swensen','Allocation','포트폴리오 설계','서로 다른 위험원을 가졌는가?']];
window.PARTS=PARTS;window.MASTERS=MASTERS;
