const CASE_KEY='investmaster-cases-v1';
const caseState=JSON.parse(localStorage.getItem(CASE_KEY)||'{"answers":{},"facts":[],"inferences":[],"memo":"","completed":[],"mistakes":[]}');
const persistCase=()=>localStorage.setItem(CASE_KEY,JSON.stringify(caseState));
const colors={SPX:'#8d9aa5',SOX:'#f5b64a',KOSPI:'#80a5d5','SK hynix':'#79d49b',Samsung:'#b78cff',USDKRW:'#e56c77',VIX:'#df709f'};
const series={
 SPX:[100,105.4,99.2,105.3,102.5,106.1,107.7,108,114.9,118.5,116.4],
 SOX:[100,115.6,105.6,128.5,126.3,134.7,124.9,146,153.2,154.2,153.6],
 KOSPI:[100,90.4,98.1,97.6,100.2,101.2,104.2,103.7,106.5,103.4,99.7],
 'SK hynix':[100,88.2,104.1,105.2,104.2,105.3,127.8,135.5,145.2,143.3,134.9],
 Samsung:[100,88.9,98.7,97.4,102.9,105.3,114.8,116.1,112.2,107.6,110],
 USDKRW:[100,92.4,88.5,86.5,92.9,91.5,93.9,93,92.5,89.4,92.8],
 VIX:[100,79.5,83.7,75,80,72.3,61,69.3,52.5,52.7,52.4]
};
const dates=['22.10','22.11','22.12','23.01','23.02','23.03','23.04','23.05','23.06','23.07','23.08'];
const lenses=[
 {name:'Market',title:'누가 가장 많이가 아니라, 누가 먼저 강해졌을까?',symbols:['SPX','SOX','SK hynix','Samsung'],concepts:['LEADING','RELATIVE STRENGTH','RECOVERY'],questions:['저점 이후 가장 먼저 직전 고점을 회복한 자산은 무엇인가?','2023년 3월 충격 이후 회복 속도는 어떻게 달랐는가?','5월 이벤트 이전부터 상대강도 차이가 벌어졌는가?','한 종목 리더십인가, 업종으로 확산된 움직임인가?'],event:{index:7,label:'NVIDIA 실적'},explain:['SOX와 SK hynix의 상대강도는 5월 확인 이벤트보다 먼저 확대되기 시작했습니다.','SOX의 절대수익률과 SOX의 업종 확산을 구분해야 합니다.','실적은 랠리의 유일한 시작점이라기보다 기존 기대를 강하게 확인한 사건으로 볼 여지가 있습니다.'],signals:['1st · SOX 회복','2nd · SK hynix 상대강도','Confirm · 5월 실적']},
 {name:'Cross Asset',title:'주가·환율·변동성은 같은 Risk-On을 말했을까?',symbols:['SPX','SOX','USDKRW','VIX'],concepts:['DIVERGENCE','REGIME','CROSS ASSET'],questions:['VIX가 낮아지는 동안 SPX와 SOX의 회복 속도는 같았는가?','원달러와 반도체의 단순 역관계가 깨진 구간은 언제인가?','네 자산 중 선택적 Risk-On을 가장 잘 보여준 조합은 무엇인가?'],event:{index:5,label:'SVB 충격'},explain:['2023년 봄 이후 VIX는 낮아졌지만 SOX의 상대강도는 SPX보다 훨씬 컸습니다.','원달러 방향 하나로 한국 반도체를 설명하기보다 미국 업종 신호와 변동성을 함께 봐야 합니다.','같은 Risk-On 안에서도 시장 전체와 특정 업종의 강도는 달랐습니다.'],signals:['Volatility · VIX ↓','Leader · SOX','Divergence · USDKRW / Semi']},
 {name:'AI / Semi',title:'한 종목의 랠리가 생태계로 확산됐을까?',symbols:['SOX','SK hynix','Samsung','KOSPI'],concepts:['BREADTH','ROTATION','EXPANSION'],questions:['NVDA 외 Compute와 Networking도 함께 강해졌는가?','Memory와 Equipment는 언제부터 확산에 참여했는가?','동시에 움직였는가, 리더에서 후발 그룹으로 순차 확산됐는가?'],event:{index:7,label:'NVIDIA 실적'},explain:['초기 리더는 NVDA였지만 AMD·AVGO와 장비주도 후속 상승에 참여했습니다.','MU의 상대강도는 초기 리더보다 늦어, 동시 상승이 아닌 순차적 확산으로 읽을 수 있습니다.','Breadth는 종목 수만이 아니라 산업 사슬의 어느 구간까지 번졌는지 봅니다.'],signals:['Leader · Compute','Expansion · Network / Equipment','Later · Memory']},
 {name:'Psychology',title:'좋은 뉴스 뒤, 갭을 지킨 시장은 무엇을 말했을까?',symbols:['SOX','SK hynix','SPX','KOSPI'],concepts:['GAP HOLD','EXPECTATION RESET','CONFIRMATION'],questions:['이벤트 이후 상승분을 되돌렸는가, 새로운 가격대를 유지했는가?','뉴스 전 가격과 뉴스 후 가격 중 어느 구간에서 기대 변화가 더 컸는가?','이 뉴스는 시작점인가, 확인점인가?'],event:{index:7,label:'실적 / 가이던스'},explain:['이벤트 이후 갭을 유지한 움직임은 장기 기대치가 재평가됐을 가능성을 시사합니다.','다만 가격만으로 원인을 확정할 수는 없습니다. 뉴스 공개 후 실적과 가이던스를 대조해야 합니다.'],signals:['Before · 선행 강세','Event · 기대 재설정','After · 갭 유지']},
 {name:'Korea',title:'미국의 반도체 신호는 한국에서 어디로 먼저 갔을까?',symbols:['SOX','SK hynix','Samsung','KOSPI'],concepts:['SIGNAL PROPAGATION','LOCAL LEADER','BROADENING'],questions:['SK hynix와 Samsung 중 상대강도가 먼저 높아진 자산은 무엇인가?','SOX 신호와 한국 반도체의 움직임 사이에 시차가 있는가?','KOSPI 전체로 같은 강도가 확산됐는가?'],event:{index:7,label:'AI 수요 확인'},explain:['SK hynix가 Samsung과 KOSPI보다 높은 상대강도를 보이며 미국 신호를 더 민감하게 반영했습니다.','이는 한국시장 전체 Risk-On보다 AI 메모리 노출의 선택적 강세로 해석할 여지가 있습니다.'],signals:['US Leader · SOX','Korea Leader · SK hynix','Breadth · KOSPI 제한']},
 {name:'FX',title:'원화 약세인데도 반도체가 오른 구간은 무엇을 뜻할까?',symbols:['USDKRW','KOSPI','SK hynix','Samsung'],concepts:['RULE BREAK','RELATIVE FORCE','FX'],questions:['USDKRW 상승과 SK hynix 상승이 겹치는 구간이 있는가?','환율과 한국주식의 단순 역관계가 어디서 깨졌는가?','업황 기대가 환율 부담보다 강했다고 추론할 근거는 무엇인가?'],event:{index:7,label:'AI 실적 확인'},explain:['원화 약세와 SK hynix 강세가 공존한 구간은 단순한 달러 공식의 예외입니다.','Fact는 두 가격이 함께 올랐다는 것이고, 업황 기대가 우위였다는 문장은 Inference입니다.'],signals:['Fact · USDKRW ↑','Fact · Hynix ↑','Inference · 업황 기대 우위']},
 {name:'Volatility',title:'시장 전체 Risk-On인가, 선택적 Risk-On인가?',symbols:['VIX','SPX','SOX','KOSPI'],concepts:['RECOVERY SPEED','SELECTIVE RISK-ON','BREADTH'],questions:['VIX 충격 이후 가장 빨리 회복한 위험자산은 무엇인가?','SPX와 SOX의 회복 속도 차이는 얼마나 벌어졌는가?','낮은 VIX와 모든 업종의 강세는 같은 뜻인가?'],event:{index:5,label:'은행 스트레스'},explain:['변동성 충격 후 SOX의 회복 속도가 SPX보다 빨랐습니다.','VIX 하락은 시장 전체의 위험선호 개선을 시사할 수 있지만, 리더십이 좁다면 선택적 Risk-On과 구분해야 합니다.'],signals:['Shock · VIX spike','Recovery · SOX first','Regime · Selective Risk-On']},
 {name:'Cross Lens',title:'각 시장의 신호를 하나의 선후관계로 연결하면?',symbols:['SOX','SK hynix','USDKRW','KOSPI'],concepts:['SEQUENCE','CONFIRMATION','TRANSMISSION'],questions:['첫 신호, 확인, 확산, 한국 전달을 순서대로 배열해보세요.','이 흐름과 모순된 자산은 무엇이었는가?','다음번에는 어떤 자산을 선행 체크할 것인가?'],event:{index:7,label:'확인 이벤트'},explain:['가능한 서사는 SOX 회복 → SK hynix 상대강도 확대 → 실적 확인 → 한국 메모리 확산입니다.','금리 상승은 이 서사를 반박하지 못했고 오히려 어떤 힘이 더 강했는지 보여준 반대 신호가 됐습니다.'],signals:['1st · SOX','Leader · SK hynix','Confirm · Earnings','Expand · SK hynix']},
 {name:'Investor Mode',title:'2023년 4월 15일의 투자자라면 어떻게 행동할까?',symbols:['SPX','SOX','SK hynix','Samsung'],concepts:['NO LOOK-AHEAD','POSITION SIZE','INVALIDATION'],questions:['당시 보이는 정보만으로 매수·관망·매도 중 무엇을 선택할까?','SK hynix·SOX·현금 중 어떤 수단을 선택할까?','확신도와 초기 비중은 어느 정도인가?','어떤 가격 행동이 나오면 내 판단을 철회할까?'],cut:6,event:{index:7,label:'아직 알 수 없는 이벤트'},explain:['당시에는 5월 실적을 알 수 없었습니다. 따라서 강한 상대가격은 Fact지만 AI 실적 급증은 아직 가설입니다.','방향 판단과 포지션 크기를 분리하고, 확인 전에는 작은 비중을 선택하는 접근이 가능합니다.'],signals:['Known · 상대강도','Unknown · 실적 규모','Action · Size by confidence']},
 {name:'Current Compare',title:'과거의 리더십 프레임을 현재에도 적용할 수 있을까?',symbols:['SOX','SK hynix','SPX','VIX'],concepts:['REGIME FEATURES','ANALOG','DIFFERENCE'],questions:['과거 Case에서 반드시 확인해야 할 네 가지 특징은 무엇인가?','현재 비교에서 리더십 순서가 다르면 같은 Case라고 할 수 있는가?','가격 상관관계보다 중요한 Regime 특징은 무엇인가?'],event:{index:7,label:'Historical marker'},explain:['Similarity는 모양이 닮았다는 뜻이 아니라 금리 방향·리더십·Breadth·변동성 같은 특징의 조합이 유사하다는 뜻입니다.','현재 데이터가 연결되기 전에는 과거 패턴을 현재라고 가장하지 않습니다.'],signals:['Compare · Leadership','Compare · Breadth','Compare · Rates / Vol']}
];
let lensIndex=0,answerType='fact',eventsVisible=false,blind=false,lookAhead=false,hiddenSymbols=new Set();
const el=s=>document.querySelector(s);const all=s=>document.querySelectorAll(s);
function renderLens(){const l=lenses[lensIndex];el('#lensStrip').innerHTML=lenses.map((x,i)=>`<button class="${i===lensIndex?'active':''} ${caseState.completed.includes(i)?'done':''}" data-lens="${i}"><i>${String(i+1).padStart(2,'0')}</i><span>${x.name}</span></button>`).join('');all('[data-lens]').forEach(b=>b.onclick=()=>{lensIndex=+b.dataset.lens;eventsVisible=false;lookAhead=false;hiddenSymbols.clear();renderLens()});el('#lensNumber').textContent=`LENS ${String(lensIndex+1).padStart(2,'0')} · ${l.name.toUpperCase()}`;el('#lensTitle').textContent=blind?'무슨 시장 환경인지 차트만 보고 추론하세요.':l.title;el('#symbolToggles').innerHTML=l.symbols.map(s=>`<button class="active" data-symbol="${s}"><i style="background:${colors[s]}"></i>${blind?'ASSET '+(l.symbols.indexOf(s)+1):s}</button>`).join('');all('[data-symbol]').forEach(b=>b.onclick=()=>{hiddenSymbols.has(b.dataset.symbol)?hiddenSymbols.delete(b.dataset.symbol):hiddenSymbols.add(b.dataset.symbol);b.classList.toggle('active',!hiddenSymbols.has(b.dataset.symbol));drawChart()});el('#questions').innerHTML=l.questions.map((q,i)=>`<li><i>Q${i+1}</i><p>${q}</p></li>`).join('');el('#caseAnswer').value=caseState.answers[lensIndex]||'';el('#caseMemo').value=caseState.memo||'';el('#coachFeedback').className='coach-feedback locked';el('#coachFeedback').innerHTML='<div class="feedback-lock">답변을 제출하면 코치의 피드백을 볼 수 있습니다.</div>';el('#explanation').className='explanation locked';el('#explanation').innerHTML='<div class="explanation-cover"><span>해설은 관찰 이후에만 공개됩니다.</span><button id="revealExplanation" disabled>해설 열기</button></div>';el('#prevLens').disabled=lensIndex===0;el('#nextLens').textContent=lensIndex===lenses.length-1?'Case 완료 →':'다음 Lens →';el('#nextPreview').textContent=lenses[Math.min(lensIndex+1,lenses.length-1)].title;el('#caseProgressBar').style.width=((lensIndex+1)/lenses.length*100)+'%';el('#caseProgressText').textContent=`${lensIndex+1} / ${lenses.length} LENS`;el('#timeCutToggle').classList.toggle('active',lookAhead);el('#timeCutToggle').textContent=lookAhead?'LOOK-AHEAD ON':'LOOK-AHEAD OFF';el('#eventToggle').textContent=eventsVisible?'EVENTS VISIBLE':'EVENTS HIDDEN';document.querySelector('.concept-badges').innerHTML=l.concepts.map(c=>`<span>${c}</span>`).join('');renderSignals();renderSupplement();drawChart()}
function renderSupplement(){const host=el('#lensSupplement');host.innerHTML='';if(lensIndex===2)host.innerHTML=`<div class="supplement-head"><span>THEME BREADTH</span><b>Single Stock → Ecosystem</b></div><div class="breadth-map"><div><small>01 · LEADER</small><b>Compute</b><span class="hot">NVDA</span><span class="hot">AMD</span></div><i>→</i><div><small>02 · CONFIRM</small><b>Network</b><span class="warm">AVGO</span><span class="warm">MRVL</span></div><i>→</i><div><small>03 · EXPAND</small><b>Equipment</b><span class="warm">LRCX</span><span class="warm">AMAT</span></div><i>→</i><div><small>04 · LATER</small><b>Memory</b><span>MU</span><span>SK hynix</span></div></div>`;if(lensIndex===7)host.innerHTML=`<div class="supplement-head"><span>NARRATIVE GRAPH</span><b>선후관계를 먼저 읽으세요.</b></div><div class="narrative-flow"><span><i>1st Signal</i>SOX 회복</span><b>→</b><span><i>Leadership</i>SK hynix 상대강도</span><b>→</b><span><i>Confirmation</i>실적</span><b>→</b><span><i>Expansion</i>SK hynix</span></div>`;if(lensIndex===8)host.innerHTML=`<div class="supplement-head"><span>HISTORICAL INVESTOR MODE</span><b>미래를 보지 않고 결정하세요.</b></div><div class="investor-mode"><div class="trade-choice"><button>매수</button><button>관망</button><button>매도</button></div><label>Position confidence <input type="range" min="1" max="5" value="2"><span>낮음 — 확인 전 작은 포지션</span></label><button id="activateCut">2023.04 이후 데이터 숨기기</button></div>`;const cut=el('#activateCut');if(cut)cut.onclick=()=>{lookAhead=true;renderLens()}}
function drawChart(){const l=lenses[lensIndex],svg=el('#marketChart'),width=900,height=390,pad={l:28,r:22,t:22,b:34},cut=lookAhead&&l.cut?l.cut:10,visible=l.symbols.filter(s=>!hiddenSymbols.has(s)),values=visible.flatMap(s=>series[s].slice(0,cut+1)),min=Math.min(75,...values),max=Math.max(125,...values),x=i=>pad.l+i/10*(width-pad.l-pad.r),y=v=>pad.t+(max-v)/(max-min)*(height-pad.t-pad.b);let out='';[0,.25,.5,.75,1].forEach(t=>{const yy=pad.t+t*(height-pad.t-pad.b);out+=`<line x1="${pad.l}" y1="${yy}" x2="${width-pad.r}" y2="${yy}" class="grid-line"/>`});dates.forEach((d,i)=>{if(i%2===0||i===10)out+=`<text x="${x(i)}" y="${height-9}" class="axis-text" text-anchor="middle">${d}</text>`});out+=`<line x1="${pad.l}" y1="${y(100)}" x2="${width-pad.r}" y2="${y(100)}" class="base-line"/><text x="${pad.l+4}" y="${y(100)-7}" class="base-label">BASE 100</text>`;visible.forEach(s=>{const vals=series[s].slice(0,cut+1),points=vals.map((v,i)=>`${x(i)},${y(v)}`).join(' ');out+=`<polyline points="${points}" fill="none" stroke="${colors[s]}" stroke-width="${s===l.symbols[0]?3:2.2}" class="series-line" data-chart-series="${s}"/>`;vals.forEach((v,i)=>out+=`<circle cx="${x(i)}" cy="${y(v)}" r="9" fill="transparent" data-point="${s}|${i}|${v}"/>`);const last=vals.length-1;out+=`<text x="${x(last)+6}" y="${y(vals[last])-6}" fill="${colors[s]}" class="end-label">${blind?'A'+(l.symbols.indexOf(s)+1):s}</text>`});if(eventsVisible&&!blind&&(!lookAhead||!l.cut||l.event.index<=cut)){const ex=x(l.event.index);out+=`<line x1="${ex}" y1="${pad.t}" x2="${ex}" y2="${height-pad.b}" class="event-line"/><rect x="${Math.min(ex+7,730)}" y="32" width="145" height="26" rx="3" class="event-box"/><text x="${Math.min(ex+17,740)}" y="49" class="event-text">${l.event.label}</text>`}if(lookAhead&&l.cut){const cx=x(l.cut);out+=`<rect x="${cx}" y="${pad.t}" width="${width-pad.r-cx}" height="${height-pad.t-pad.b}" class="future-mask"/><text x="${cx+20}" y="${height/2}" class="future-text">FUTURE DATA HIDDEN</text>`}svg.innerHTML=out;all('[data-point]').forEach(p=>{p.onmouseenter=e=>{const [s,i,v]=p.dataset.point.split('|');el('#chartTooltip').innerHTML=`<b>${blind?'ASSET '+(l.symbols.indexOf(s)+1):s}</b><span>${dates[i]} · ${(+v-100)>=0?'+':''}${(+v-100).toFixed(1)}%</span>`;el('#chartTooltip').style.cssText=`display:block;left:${Math.min(e.offsetX+20,760)}px;top:${Math.max(10,e.offsetY-35)}px`};p.onmouseleave=()=>el('#chartTooltip').style.display='none'})}
function submit(){const text=el('#caseAnswer').value.trim();if(text.length<8){el('#saveStatus').textContent='조금 더 구체적으로 적어주세요';return}caseState.answers[lensIndex]=text;const bucket=answerType==='fact'?'facts':'inferences';caseState[bucket]=caseState[bucket].filter(x=>x.lens!==lensIndex);caseState[bucket].push({lens:lensIndex,text});persistCase();const temporal=/먼저|이후|전부터|빠르|저점|돌파|회복|시점/.test(text),causal=/때문|기대|선반영|영향|것 같다|추론/.test(text);if(answerType==='fact'&&causal)caseState.mistakes.push('Fact와 원인 추론 혼합');if(!temporal)caseState.mistakes.push('선후관계 확인 부족');persistCase();el('#coachFeedback').className='coach-feedback';el('#coachFeedback').innerHTML=`<div class="coach-title"><span>AI COACH · 관찰 피드백</span><b>정답은 아직 공개하지 않습니다.</b></div><div class="feedback-grid"><article><i>잘 본 점</i><p>${temporal?'선후관계와 회복 시점을 보려는 관찰이 들어 있습니다.':'자산 간 움직임의 차이를 자신의 언어로 기록했습니다.'}</p></article><article><i>다시 볼 점</i><p>${temporal?'가장 많이 오른 자산과 가장 먼저 움직인 자산을 다시 분리해보세요.':'“언제부터” 차이가 벌어졌는지 날짜 순서를 한 번 더 확인하세요.'}</p></article><article><i>구분해야 할 개념</i><p>${answerType==='fact'&&causal?'가격에서 직접 본 사실과 그 원인에 대한 추론이 한 문장에 섞여 있습니다.':'절대수익률과 상대강도, 선행성과 최종수익률은 서로 다릅니다.'}</p></article></div>`;el('#explanation').className='explanation';el('#explanation').innerHTML='<div class="explanation-cover"><span>관찰을 제출했습니다. 준비되면 해설을 확인하세요.</span><button id="revealExplanation">해설 열기</button></div>';el('#revealExplanation').onclick=reveal;renderNotes()}
function reveal(){const l=lenses[lensIndex];el('#explanation').innerHTML=`<div class="explanation-head"><p class="eyebrow">REVEAL · INTERPRETATION</p><h2>${blind?l.name+' Lens':l.title}</h2></div><ol>${l.explain.map((x,i)=>`<li><i>0${i+1}</i><p>${x}</p></li>`).join('')}</ol><div class="fact-inference"><div><span class="badge fact">FACT</span><p>차트에서 직접 확인한 가격·순서·상대강도</p></div><div><span class="badge inference">INFERENCE</span><p>그 움직임이 반영했다고 추정하는 기대와 원인</p></div></div>`;eventsVisible=true;if(!caseState.completed.includes(lensIndex))caseState.completed.push(lensIndex);persistCase();drawChart();renderLensTabsOnly()}
function renderLensTabsOnly(){all('[data-lens]').forEach((b,i)=>b.classList.toggle('done',caseState.completed.includes(i)))}
function renderNotes(){const render=(id,items)=>{el(id).innerHTML=items.length?items.map(x=>`<button data-go-lens="${x.lens}"><b>L${x.lens+1}</b><span>${x.text}</span></button>`).join(''):'<p>아직 기록이 없습니다.</p>'};render('#factNotes',caseState.facts);render('#inferenceNotes',caseState.inferences);all('[data-go-lens]').forEach(b=>b.onclick=()=>{lensIndex=+b.dataset.goLens;renderLens()})}
function renderSignals(){el('#signalStack').innerHTML=lenses[lensIndex].signals.map((s,i)=>`<div><i>${i+1}</i><span>${blind?'SIGNAL '+(i+1):s}</span></div>`).join('')}
function secondary(view){el('#workspaceView').hidden=true;el('#secondaryView').hidden=false;const views={current:['CURRENT MARKET','실시간 데이터 연결 전','현재 시장을 과거처럼 가장하지 않습니다. 데이터 공급자 연결 후 강한 자산·금리·DXY·VIX·Credit·Breadth를 자동 계산합니다.','현재 시장에서 가장 이상한 움직임은 무엇인가?'],library:['CASE LIBRARY','역사적 사건으로 훈련하기','경제학 목차가 아니라 실제 시장 사건과 필요한 Lens로 구성합니다.','2023 AI Rally · 2022 Rate Shock · 2020 Liquidity Shock · 2013 Taper Tantrum · 2023 SVB'],notebook:['MY NOTEBOOK','생각이 바뀐 흔적','처음 생각, 수정된 생각, 실수와 현재시장 적용을 Case별로 저장합니다.',`저장된 Fact ${caseState.facts.length}개 · Inference ${caseState.inferences.length}개 · 완료 Lens ${caseState.completed.length}개`],blind:['BLIND TEST','날짜와 사건을 가리고 추론하기','사건명을 숨긴 채 Cross Asset의 순서와 Regime을 맞혀보세요.','상단 BLIND 버튼을 켜고 Case Study로 돌아가세요.'],symbols:['MARKET SYMBOLS','최소한의 시장 언어','자산 이름보다 각 자산이 어떤 기대에 민감한지 기억합니다.','SPX · NDX · SOX / US02Y · US10Y / DXY · USDKRW / Gold · Oil / VIX · MOVE / HYG / KOSPI · Nikkei'],weakness:['MY WEAKNESSES','반복되는 사고 오류',caseState.mistakes.length?'작성한 답변에서 반복 패턴을 찾았습니다.':'답변이 쌓이면 AI Coach가 반복 오류를 분류합니다.',caseState.mistakes.length?[...new Set(caseState.mistakes)].join(' · '):'수익률과 선행성 혼동 · Fact와 Inference 혼합 · Breadth 누락 등을 추적합니다.']};const v=views[view];el('#secondaryView').innerHTML=`<section class="secondary-hero"><p class="eyebrow">${v[0]}</p><h1>${v[1]}</h1><p>${v[2]}</p></section><section class="secondary-card"><span>WORKSPACE NOTE</span><p>${v[3]}</p>${view==='current'?'<button class="button outline" disabled>DATA PROVIDER REQUIRED</button>':''}</section>`}
all('[data-view]').forEach(b=>b.onclick=()=>{all('[data-view]').forEach(x=>x.classList.toggle('active',x===b));if(b.dataset.view==='case'){el('#workspaceView').hidden=false;el('#secondaryView').hidden=true}else secondary(b.dataset.view)});all('[data-answer-type]').forEach(b=>b.onclick=()=>{answerType=b.dataset.answerType;all('[data-answer-type]').forEach(x=>x.classList.toggle('active',x===b));el('#caseAnswer').placeholder=answerType==='fact'?'차트에서 직접 확인한 사실부터 적어보세요.':'그 사실이 의미하는 시장의 기대를 가설로 적어보세요.'});el('#caseAnswer').oninput=()=>{caseState.answers[lensIndex]=el('#caseAnswer').value;persistCase();el('#saveStatus').textContent='저장됨 ✓'};el('#caseMemo').oninput=()=>{caseState.memo=el('#caseMemo').value;persistCase()};el('#submitAnswer').onclick=submit;el('#eventToggle').onclick=()=>{eventsVisible=!eventsVisible;el('#eventToggle').textContent=eventsVisible?'EVENTS VISIBLE':'EVENTS HIDDEN';drawChart()};el('#blindToggle').onclick=()=>{blind=!blind;el('#blindToggle').classList.toggle('active',blind);el('#blindToggle').innerHTML=`<i></i> BLIND ${blind?'ON':'OFF'}`;el('#caseTitle').textContent=blind?'CASE 001 · UNKNOWN':'2023 AI Rally';el('#caseIntro').textContent=blind?'날짜·사건·심볼을 숨겼습니다. 가격의 순서만 보고 시장 환경을 추론하세요.':'금리 부담 속에서 시작된 선택적 기술주 랠리. 아직 사건명보다 차트의 순서를 먼저 보세요.';renderLens()};el('#timeCutToggle').onclick=()=>{lookAhead=!lookAhead;renderLens()};el('#resetChart').onclick=()=>{hiddenSymbols.clear();eventsVisible=false;lookAhead=false;renderLens()};el('#prevLens').onclick=()=>{if(lensIndex>0){lensIndex--;renderLens();scrollTo({top:70,behavior:'smooth'})}};el('#nextLens').onclick=()=>{if(lensIndex<lenses.length-1){lensIndex++;renderLens();scrollTo({top:70,behavior:'smooth'})}else secondary('notebook')};el('#themeToggle').onclick=()=>document.body.classList.toggle('light-practice');el('#caseMemo').value=caseState.memo;renderLens();renderNotes();
