const artifacts=[
 {title:'Investment Philosophy',kicker:'01 · NORTH STAR',desc:'어떤 시장에서 어떤 방식으로 우위를 만들지 정의합니다.',fields:[['Universe','내가 이해하고 지속적으로 추적할 시장과 기업'],['Style','Quality Growth, Value, Momentum 등 주된 접근'],['Edge','정보·분석·행동·시간 중 내가 가진 우위'],['Do not','내가 하지 않을 투자와 넘지 않을 경계']]},
 {title:'기업분석 템플릿',kicker:'02 · BUSINESS',desc:'숫자와 이야기, 기대와 위험을 한 장에 정리합니다.',fields:[['Business model','누가 왜 돈을 내며 매출은 어떻게 만들어지는가'],['Moat','초과수익을 지키는 구조와 약화 신호'],['Economics','ROIC, FCF conversion, 재투자 공간'],['Red team','내 논리를 깨는 가장 강한 반대 근거']]},
 {title:'Valuation Model',kicker:'03 · PRICE',desc:'가격에 반영된 기대와 내가 요구하는 수익률을 연결합니다.',fields:[['Method','Comparable, DCF, Reverse DCF 중 선택 이유'],['Key assumptions','성장률, 마진, 할인율, 지속기간'],['Expectation gap','시장 기대와 내 추정의 차이'],['Buy range','오차와 안전마진을 반영한 가격 범위']]},
 {title:'Portfolio Rules',kicker:'04 · RISK',desc:'확신과 별개로 생존을 보장하는 포지션 규칙을 만듭니다.',fields:[['Initial size','첫 매수 비중과 근거'],['Maximum size','단일 포지션 최대 비중'],['Add / reduce','비중을 늘리고 줄이는 조건'],['Risk budget','아이디어 하나에서 감수할 최대 손실']]},
 {title:'Investment Journal',kicker:'05 · FEEDBACK',desc:'결정 당시의 정보와 사후 결과를 분리해 학습합니다.',fields:[['Before','사실, 시장 예상, 내 예상'],['Invalidation','내가 틀렸음을 인정할 관찰 가능한 조건'],['After','Thesis 결과와 투자 수익을 각각 평가'],['Lesson','운과 실력을 분리한 다음 행동 변화']]},
 {title:'거장별 Playbook',kicker:'06 · SYNTHESIS',desc:'거장의 도구 중 내 시스템과 양립하는 것만 남깁니다.',fields:[['Use','가져올 거장과 구체적인 도구'],['When','그 도구가 작동할 시장과 상황'],['Conflict','내 다른 규칙과 충돌하는 지점'],['My rule','내 언어로 다시 쓴 실행 규칙']]}
];let current=0;
function renderNav(){document.querySelector('#artifactNav').innerHTML=artifacts.map((a,i)=>`<button class="${i===current?'active':''}" data-artifact="${i}"><i>0${i+1}</i><span>${a.title}</span><b>${a.fields.every(f=>imState.notes[`artifact-${i}-${f[0]}`])?'완성':'작성 중'}</b></button>`).join('');document.querySelectorAll('[data-artifact]').forEach(b=>b.onclick=()=>{current=+b.dataset.artifact;renderNav();render()})}
function render(){const a=artifacts[current];document.querySelector('#artifactNo').textContent=`0${current+1}`;document.querySelector('#artifactKicker').textContent=a.kicker;document.querySelector('#artifactTitle').textContent=a.title;document.querySelector('#builderBody').innerHTML=`<p class="builder-desc">${a.desc}</p>${a.fields.map(([name,hint],i)=>`<label class="builder-field"><span><b>${String(i+1).padStart(2,'0')}</b><strong>${name}</strong><small>${hint}</small></span><textarea data-field="${name}" placeholder="나의 원칙을 구체적인 문장으로 적으세요."></textarea></label>`).join('')}<div class="builder-save"><span>입력 내용은 이 브라우저에 자동 저장됩니다.</span><button id="finishArtifact">이 문서를 완성으로 표시</button></div>`;document.querySelectorAll('[data-field]').forEach(x=>{const key=`artifact-${current}-${x.dataset.field}`;x.value=imState.notes[key]||'';x.oninput=()=>{imState.notes[key]=x.value;saveState();renderNav()}});const finish=document.querySelector('#finishArtifact'),copy=document.querySelector('#copyArtifact');finish.onclick=()=>{const k='artifact-'+current;if(!imState.completed.includes(k))imState.completed.push(k);saveState();finish.textContent='✓ 완성됨'};copy.onclick=async()=>{const text=[a.title,...a.fields.map(([n])=>`${n}\n${imState.notes[`artifact-${current}-${n}`]||''}`)].join('\n\n');try{await navigator.clipboard.writeText(text);copy.textContent='복사됨 ✓'}catch{copy.textContent='복사할 수 없음'}}}
const edges=[['Information Edge','남보다 좋은 정보를 지속적으로 얻는가?'],['Analytical Edge','같은 정보를 더 정확히 해석하는가?'],['Behavioral Edge','남들이 견디지 못할 변동성을 견디는가?'],['Time Horizon Edge','결과가 나타날 때까지 더 오래 기다리는가?']];document.querySelector('#edgeGrid').innerHTML=edges.map(([a,b],i)=>`<label><input type="radio" name="edge" value="${a}"><span><i>0${i+1}</i><b>${a}</b><small>${b}</small></span></label>`).join('');document.querySelectorAll('[name=edge]').forEach(x=>{x.checked=imState.rules.edge===x.value;x.onchange=()=>{imState.rules.edge=x.value;saveState()}});renderNav();render();updateGlobalProgress();
