const artifacts=[
 {title:'Investment Philosophy',kicker:'01 · NORTH STAR',desc:'어떤 시장에서 어떤 방식으로 우위를 만들지 정의합니다.',fields:[['Universe','내가 이해하고 지속적으로 추적할 시장과 기업','예: 시가총액 1조원 이상, 내가 매출 구조를 한 문장으로 설명할 수 있는 국내외 상장기업.'],['Style','Quality Growth, Value, Momentum 등 주된 접근','예: ROIC 15% 이상을 5년 이상 유지한 Quality 기업을 합리적 가격에 사서 3년 이상 보유하는 Quality Growth.'],['Edge','정보·분석·행동·시간 중 내가 가진 우위','예: 회계와 산업 분석에 쓸 수 있는 시간(Analytical Edge)과, 남들이 견디지 못하는 변동성을 버티는 행동적 우위(Behavioral Edge).'],['Do not','내가 하지 않을 투자와 넘지 않을 경계','예: 내가 이해하지 못하는 파생상품에 투자하지 않는다. 하락장에서 레버리지를 쓰지 않는다.']]},
 {title:'기업분석 템플릿',kicker:'02 · BUSINESS',desc:'숫자와 이야기, 기대와 위험을 한 장에 정리합니다.',fields:[['Business model','누가 왜 돈을 내며 매출은 어떻게 만들어지는가','예: B2C 구독 서비스로, 월 구독료 × 가입자 수가 매출을 결정하며 한계비용이 낮아 규모의 경제가 작동한다.'],['Moat','초과수익을 지키는 구조와 약화 신호','예: 전환비용(Switching cost)과 데이터 네트워크효과가 경쟁우위를 지키고 있으나, 대형 플랫폼의 번들링 전략이 약화 신호다.'],['Economics','ROIC, FCF conversion, 재투자 공간','예: ROIC 22%, FCF 전환율 85%, 매출 대비 재투자 CapEx 8%로 재투자 여력이 충분하다.'],['Red team','내 논리를 깨는 가장 강한 반대 근거','예: 핵심 고객층의 이탈률이 최근 2분기 연속 상승 중이며, 이는 Moat이 이미 약해지고 있다는 신호일 수 있다.']]},
 {title:'Valuation Model',kicker:'03 · PRICE',desc:'가격에 반영된 기대와 내가 요구하는 수익률을 연결합니다.',fields:[['Method','Comparable, DCF, Reverse DCF 중 선택 이유','예: 안정적 현금흐름을 감안해 DCF를 기본으로 쓰되, 동종업계 대비 상대가치는 Comparable로 교차 검증한다.'],['Key assumptions','성장률, 마진, 할인율, 지속기간','예: 5년 매출 성장률 12%, 영업마진 25%로 수렴, 할인율(WACC) 9%, Terminal 성장률 2.5%.'],['Expectation gap','시장 기대와 내 추정의 차이','예: 현재 주가는 연 18% 성장을 요구하지만 내 추정은 연 12%로, 6%p의 기대 격차가 존재한다.'],['Buy range','오차와 안전마진을 반영한 가격 범위','예: 안전마진 25%를 반영해 내재가치 대비 75% 이하에서만 매수를 시작한다.']]},
 {title:'Portfolio Rules',kicker:'04 · RISK',desc:'확신과 별개로 생존을 보장하는 포지션 규칙을 만듭니다.',fields:[['Initial size','첫 매수 비중과 근거',"예: 확신도 '보통' 아이디어는 포트폴리오의 2%, '높음'은 5%로 시작한다."],['Maximum size','단일 포지션 최대 비중','예: 단일 종목 비중은 아무리 확신해도 15%를 넘기지 않는다.'],['Add / reduce','비중을 늘리고 줄이는 조건','예: 실적이 내 논리를 재확인하면 비중을 5%p 늘리고, 핵심 가정이 틀렸다는 증거가 나오면 즉시 절반으로 줄인다.'],['Risk budget','아이디어 하나에서 감수할 최대 손실','예: 아이디어 하나에서 감수할 최대 손실은 전체 포트폴리오의 3%를 넘지 않는다.']]},
 {title:'Investment Journal',kicker:'05 · FEEDBACK',desc:'결정 당시의 정보와 사후 결과를 분리해 학습합니다.',fields:[['Before','사실, 시장 예상, 내 예상','예: [사실] 매출 20% 성장, 재고 35% 증가 / [시장 예상] 마진 개선 기대 / [내 예상] 재고 증가는 수요 둔화 신호로 마진 악화 예상.'],['Invalidation','내가 틀렸음을 인정할 관찰 가능한 조건','예: 다음 분기 재고자산회전율이 개선되고 매출채권 증가율이 매출 성장률 아래로 내려오면 내 논리는 틀린 것으로 인정한다.'],['After','Thesis 결과와 투자 수익을 각각 평가','예: [Thesis] 재고 신호대로 마진은 악화됐으나 [투자 수익] 주가는 시장 전체 랠리로 오히려 상승 — 논리는 맞았지만 결과는 운이 도왔다.'],['Lesson','운과 실력을 분리한 다음 행동 변화','예: 논리가 맞았어도 수익이 났다고 다음에 안전마진 없이 베팅 크기를 키우지 않는다.']]},
 {title:'거장별 Playbook',kicker:'06 · SYNTHESIS',desc:'거장의 도구 중 내 시스템과 양립하는 것만 남깁니다.',fields:[['Use','가져올 거장과 구체적인 도구','예: Klarman의 틀렸을 때 얼마를 잃는가 질문을 모든 매수 전 체크리스트 첫 항목으로 가져온다.'],['When','그 도구가 작동할 시장과 상황','예: 밸류에이션 매력은 있지만 가격 추세가 아직 반대일 때, 안전마진을 계산한 뒤 분할 매수 규칙으로 진입한다.'],['Conflict','내 다른 규칙과 충돌하는 지점','예: Minervini의 추세 확인 후 매수는 내 장기 가치투자 규칙의 싸면 분할 매수 시작과 타이밍 기준이 충돌한다.'],['My rule','내 언어로 다시 쓴 실행 규칙','예: 밸류에이션(Klarman)으로 후보를 고르고, 가격 추세(Minervini)로 최종 진입 시점만 조정한다 — 종목 선정과 타이밍으로 역할을 분리한다.']]}
];let current=0;
function renderNav(){document.querySelector('#artifactNav').innerHTML=artifacts.map((a,i)=>`<button class="${i===current?'active':''}" data-artifact="${i}"><i>0${i+1}</i><span>${a.title}</span><b>${a.fields.every(f=>imState.notes[`artifact-${i}-${f[0]}`])?'완성':'작성 중'}</b></button>`).join('');document.querySelectorAll('[data-artifact]').forEach(b=>b.onclick=()=>{current=+b.dataset.artifact;renderNav();render()})}
function render(){const a=artifacts[current];document.querySelector('#artifactNo').textContent=`0${current+1}`;document.querySelector('#artifactKicker').textContent=a.kicker;document.querySelector('#artifactTitle').textContent=a.title;document.querySelector('#builderBody').innerHTML=`<p class="builder-desc">${a.desc}</p>${a.fields.map(([name,hint,example],i)=>`<label class="builder-field"><span><b>${String(i+1).padStart(2,'0')}</b><strong>${name}</strong><small>${hint}</small></span><div><textarea data-field="${name}" placeholder="나의 원칙을 구체적인 문장으로 적으세요."></textarea>${exampleBlock('artifact-'+current+'-'+name,example)}</div></label>`).join('')}<div class="builder-save"><span>입력 내용은 이 브라우저에 자동 저장됩니다.</span><button id="finishArtifact">이 문서를 완성으로 표시</button></div>`;document.querySelectorAll('[data-field]').forEach(x=>{const key=`artifact-${current}-${x.dataset.field}`;x.value=imState.notes[key]||'';x.oninput=()=>{imState.notes[key]=x.value;saveState();renderNav()}});wireExamples();const finish=document.querySelector('#finishArtifact'),copy=document.querySelector('#copyArtifact');finish.onclick=()=>{const k='artifact-'+current;if(!imState.completed.includes(k))imState.completed.push(k);saveState();finish.textContent='✓ 완성됨'};copy.onclick=async()=>{const text=[a.title,...a.fields.map(([n])=>`${n}\n${imState.notes[`artifact-${current}-${n}`]||''}`)].join('\n\n');try{await navigator.clipboard.writeText(text);copy.textContent='복사됨 ✓'}catch{copy.textContent='복사할 수 없음'}}}
const edges=[['Information Edge','남보다 좋은 정보를 지속적으로 얻는가?'],['Analytical Edge','같은 정보를 더 정확히 해석하는가?'],['Behavioral Edge','남들이 견디지 못할 변동성을 견디는가?'],['Time Horizon Edge','결과가 나타날 때까지 더 오래 기다리는가?']];document.querySelector('#edgeGrid').innerHTML=edges.map(([a,b],i)=>`<label><input type="radio" name="edge" value="${a}"><span><i>0${i+1}</i><b>${a}</b><small>${b}</small></span></label>`).join('');document.querySelectorAll('[name=edge]').forEach(x=>{x.checked=imState.rules.edge===x.value;x.onchange=()=>{imState.rules.edge=x.value;saveState()}});renderNav();render();updateGlobalProgress();
